# Generated by Django 2.2.6 on 2019-10-11 20:11

from django.db import migrations, models
from faker import Faker

def insert_common_employees(apps, schema_editor):
    fake = Faker()
    User = apps.get_model('watson_comunnication', 'User')
    for _ in range(3):
        user = User(name= fake.name(), email= fake.email(), phone_number= fake.msisdn())
        user.save()

class Migration(migrations.Migration):
    dependencies = [
        ('watson_comunnication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionandanswer',
            name='data',
            field=models.DateField(auto_now=True),
        ),
        migrations.RunPython(insert_common_employees) 
    ]
